"""initial schema

Revision ID: 97c4eb531e30
Revises: 
Create Date: 2026-06-27 01:12:16.855316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c4eb531e30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('owner_telegram_id', sa.String(length=64), nullable=False),
    sa.Column('owner_display_name', sa.String(length=255), nullable=True),
    sa.Column('gst_session_token', sa.String(length=512), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_index(op.f('ix_businesses_gstin'), 'businesses', ['gstin'], unique=True)
    op.create_index(op.f('ix_businesses_owner_telegram_id'), 'businesses', ['owner_telegram_id'], unique=True)
    op.create_table('cas',
    sa.Column('ca_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('dashboard_account_created', sa.Boolean(), nullable=False),
    sa.Column('telegram_id_for_notifications', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ca_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('suppliers',
    sa.Column('supplier_gstin', sa.String(length=15), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('gstin_status', sa.Enum('active', 'cancelled', name='gstin_status'), nullable=False),
    sa.Column('filing_history', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('last_gstin_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('supplier_gstin')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('amount_at_risk', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('open', 'reminder_sent', 'resolved', name='alert_status'), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ),
    sa.ForeignKeyConstraint(['supplier_gstin'], ['suppliers.supplier_gstin'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_business_id'), 'alerts', ['business_id'], unique=False)
    op.create_table('business_ca_links',
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('ca_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.Enum('view_only', 'can_act', name='permission_level'), nullable=False),
    sa.Column('status', sa.Enum('invited', 'accepted', 'revoked', name='link_status'), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ),
    sa.ForeignKeyConstraint(['ca_id'], ['cas.ca_id'], ),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('business_id', 'ca_id', name='uq_business_ca')
    )
    op.create_table('gst_sync_logs',
    sa.Column('sync_log_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', sa.Enum('success', 'failure', name='sync_result'), nullable=False),
    sa.Column('detail', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ),
    sa.PrimaryKeyConstraint('sync_log_id')
    )
    op.create_index(op.f('ix_gst_sync_logs_business_id'), 'gst_sync_logs', ['business_id'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('purchase', 'sale', name='invoice_direction'), nullable=False),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('counterparty_gstin', sa.String(length=15), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('taxable_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('logged', 'confirmed_by_owner', 'disputed', name='invoice_status'), nullable=False),
    sa.Column('itc_status', sa.Enum('pending_verification', 'verified_filed', 'at_risk_not_filed', name='itc_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ),
    sa.ForeignKeyConstraint(['counterparty_gstin'], ['suppliers.supplier_gstin'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index(op.f('ix_invoices_business_id'), 'invoices', ['business_id'], unique=False)
    op.create_index(op.f('ix_invoices_counterparty_gstin'), 'invoices', ['counterparty_gstin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_counterparty_gstin'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_business_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_gst_sync_logs_business_id'), table_name='gst_sync_logs')
    op.drop_table('gst_sync_logs')
    op.drop_table('business_ca_links')
    op.drop_index(op.f('ix_alerts_business_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('suppliers')
    op.drop_table('cas')
    op.drop_index(op.f('ix_businesses_owner_telegram_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_gstin'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
